#!/bin/python

import numpy as np
from scipy.signal import find_peaks

m1 = (579.0 - 546.0) / (1301.0 - 1022.0)

def rough1 ( i ) :
    rv = 546.0 + (i-1022.0) * m
    return rv

m2 = (546.0-435.8) / (1022.0-274.0)

def rough ( i ) :
    rv = 435.0 + (i-274.0) * m2
    return rv

print ( "At index 0: ", rough(0) )
print ( "At index 2047: ", rough(2047) )

def peaks ( path, h ) :
    # This gives a 2D array
    #data = np.loadtxt ( infile )

    x, y = np.loadtxt ( infile, unpack=True )

    print ( len(y), " points read from ", path );
    #print ( y[2047] )
    print ( "Min: ", np.min(y) )
    print ( "Max: ", np.max(y) )

    #peaks, properties = find_peaks ( y, height=0.5, distance=10, prominence=0.5 )
    peaks, properties = find_peaks ( y, height=h, distance=5, prominence=100.0 )

    print ( len(peaks), " peaks found" );

    for p in peaks :
        print ( p, rough(p), y[p] )

    print ( peaks )

infile = "hg1.out"
peaks ( infile, 30000.0 )
infile = "hg2.out"
peaks ( infile, 1800.0 )

# Use numpy.polyfit for least sq polynomial.

# THE END
